global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Collections;
global using System.Text;
global using SunamoCollectionWithoutDuplicates._sunamo.SunamoExceptions;
global using SunamoCollectionWithoutDuplicates._sunamo.SunamoInterfaces.Interfaces;
global using System.Diagnostics;
global using SunamoCollectionWithoutDuplicates;
global using SunamoCollectionWithoutDuplicates._sunamo.SunamoArgs;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
